theme: jekyll-theme-minimal
title: IdeaElan Drive Training
description: Training page of IdeaElan Recruitment Drive
show_downloads: false
author: 'Sathish G'
subtitle: 'RVS College of Arts and Science'
github:
  is_project_page: false
